# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52a81cb88260537b29e5b0c2127d6fc5bc7761271c94b64ab57e3ac06887833f6ea84ec5b1d083d424b6319d2494e4ae7b7c62c83f423608a9a424dd4d0699ab

test:
  secret_key_base: 62a03e623b5c4a61f4c6552f6df5b5f71d1ed1a45aeafe59639b9c1bb6b504e55ae1aa38cc593ae336969dc93f02488b985e840c74778b554827a11b23094d32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: bba690848acb8a313e0a5d4c24a5f3db44bbe251892577d842548d98108a75c05e7f5597eeafc2d404d5c125ca6b58ab07ff1a1904b32e7ecf0e17cfbbc30567
